### PR TITLE
#51 ng serve stop option

### LINKED ISSUE #51: ng-serve stop option
While the app is being `serve`ed the `serve` button should be changed to `stop` and clicking it should stop the `ng serve` process

### PR DESCRIPTION
**Pull request by ZimGil**
Not sure if I like this solution,

Couldn't find a better way to kill the process.
using `kill()` did not allow to use the same port again later.

@ortichon This PR is more for the review then actually merging for now.

resolves #51

### CODE REVIEW

**Comment by ortichon** [comment]
you can kill processes with 
[this](https://nodejs.org/api/process.html#process_process_kill_pid_signal)
you'll have to pass a PID (process id) 
we've got to have this PID when we run the process

**Comment by ZimGil** [comment]
We have the PID in `runningProcess.process.pid()` but for some reason
there is another process for `ng serve` created and this won’t kill it and
the port won’t get released

**Comment by ortichon** [comment]
> _**but for some reason**_
there is another process for `ng serve` created and this won’t kill it and
the port won’t get released

waiting to know the reason
:-)

**Comment by ZimGil** [comment]
Can't find a way to send any event signal to kill the `ng serve` process, only the command.
The only effective way I could find is the original way in this PR which was to kill any process running on the used port.

**Comment by ZimGil** [comment]
This method kills the process running on used `port` and by doing so also kills all side processes.

This is the only way I was able to kill the process and clear the port. 
I've tried it while looking into the Windows Task Manager and it seems to kill all processes started after running `ng serve` so no redundant processes stays alive.

**Comment by ZimGil** [comment]
This will also resolve #55

**Comment by ZimGil** [comment]
This has become a big mess,
I guess it's better to fix the bugs in master then working on this issue again

**Pull request closed without merging**
